### ISSUE TITLE
Paper might be making Nightly run slowly

### ISSUE THREAD

**Issue by swrobel** [yegortimoshenko/paper#3]
<img width="641" alt="screen shot 2015-07-28 at 6 48 43 pm" src="https://cloud.githubusercontent.com/assets/157270/8945869/53fdb7cc-3559-11e5-990c-1adbe2ed48f1.png">

Getting this notification on the new [e10s](https://wiki.mozilla.org/Electrolysis)-enabled nightly builds of Firefox.

**Comment by yegortimoshenko** [comment]
Will investigate. Thanks for reporting.

**Comment by yegortimoshenko** [comment]
It's due to the “shift-click a link to save it to Instapaper” feature.

If a modifier for shift-clicking (whether is it shift or any other modifier key) is specified, [`listener.js`](https://github.com/yegortimoshenko/paper/blob/master/data/listener.js) gets injected to every webpage you visit in order to catch and process your shift-click.

If you turn it off (set `Modifier` to `None`), the aforementioned `listener.js` is not injected anywhere, so all webpages you visit will run somewhat faster. And your battery will become a little bit happier as well. I don't know exact benchmarks though, I might benchmark them if you're interested.

Do you think `Modifier` should be `None` by default? I love defaults that work out of the box, but this time it conflicts with battery life and perfomance, to some degree.

**Comment by swrobel** [comment]
I think it should be None by default since this is a feature I (and probably most other users) don't know about.

**Comment by yegortimoshenko** [comment]
I have compared Firefox with Paper turned on (including this feature) and Paper turned off. This little piece of JS that is added when shift-click-to-add feature is on doesn't affect performance or energy consumption in any measurable amount, so I'm closing the issue.

I suppose that the warning message appears because it finds that Paper uses `PageMod` to inject a piece of JS at every site you visit using a wildcard `*`, which may be a bad practice, like using CSS `*` selector.
